LIBJINGLE_CPPFLAGS := -DHAMMER_TIME=1 \
	-DHASHNAMESPACE=__gnu_cxx \
	-DHASH_NAMESPACE=__gnu_cxx \
	-DDISABLE_DYNAMIC_CAST \
	-D_REENTRANT \
	-DPOSIX \
	-DOS_LINUX=OS_LINUX \
	-DLINUX \
	-DANDROID \
	-D_DEBUG \
	-DEXPAT_RELATIVE_PATH \
	-DSRTP_RELATIVE_PATH \
	-DXML_STATIC \
	-DFEATURE_ENABLE_SSL \
	-DHAVE_OPENSSL_SSL_H=1 \
	-DHAVE_SRTP \
	-DFEATURE_ENABLE_VOICEMAIL \
	-DFEATURE_ENABLE_PSTN \
	-DLOGGING=1


LIBJINGLE_C_INCLUDE:= \
	$(EXPAT_C_INCLUDE) \
	$(SRTP_C_INCLUDE) \
	$(LOCAL_PATH)/../../externals/openssl/include 	
